spring:
  application:
    name: footy-metric
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/footy_metric
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
  profiles:
    active: dev